default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :tests do
    gradle(task: "mls:test")
  end
end


platform :android do
    desc: "Publish the Release"
    late :publish do
        gradle(task: "mls:publish")
    end
end
