package tv.mycujoo.mls.entity.actions

const val ABSTRACT_ACTION_SHOW_SCOREBOARD_OVERLAY_ID = "0"
const val ABSTRACT_ACTION_SHOW_TIME_LINE_MARKER_ID = "1"
const val ABSTRACT_ACTION_SHOW_ANNOUNCEMENT_OVERLAY_ID = "2"

const val ABSTRACT_ACTION_COMMAND_ID = "3"